# Run with:
# ansible-playbook InstallApache2.yml

---
- name: Install Apache2
  hosts: all
  tasks:

  - name: Install Apache2 package on OpenSUSE/SUSE Linux
    zypper:
      name: apache2
      state: present

  - name: Install Apache2 Utils package on OpenSUSE/SUSE Linux
    zypper:
      name: apache2-utils
      state: present

  # Certbot wants this enabled
  - name: Enable the rewrite Apache2 module
    community.general.apache2_module:
      state: present
      name: rewrite
    ignore_errors: yes #BUG will error if already present

  - name: Enable the proxy Apache2 module
    community.general.apache2_module:
      state: present
      name: proxy
    ignore_errors: yes #BUG will error if already present

  - name: Enable the proxy_http Apache2 module
    community.general.apache2_module:
      state: present
      name: proxy_http
    ignore_errors: yes #BUG will error if already present

  - name: Adjust DirectoryIndex
    replace:
      path: /etc/apache2/httpd.conf
      regexp: '^DirectoryIndex index.html index.html.var'
      replace: 'DirectoryIndex index.html index.htm index.html.var'

  # Useful for debugging
  - name: Set Options All
    replace:
      path: /etc/apache2/default-server.conf
      regexp: 'Options None'
      replace: 'Options All'

  - name: Start Apache2 service
    ansible.builtin.systemd:
      state: restarted
      name: apache2

  - name: Enable Apache2 service
    ansible.builtin.systemd:
      name: apache2
      enabled: yes
